version: "3.9"
services:
  db:
    environment:
       POSTGRES_USER : postgres_dock
       POSTGRES_PASSWORD : postgres_dock
       POSTGRES_DB : postgres_dock
       POSTGRES_HOST_AUTH_METHOD : trust
    ports:
      - 5432:5432
    image: postgres:latest

  web:
    build: ./Flask
    ports:
      - 8080:8080
    depends_on:
      - db
  scrapper:
    build: ./Sreality
    ports:
      - 8000:5000
    depends_on:
      - db
    restart: "on-failure:5"